#!/usr/bin/env python3

# Import required packages
from multiprocessing import Pool
import os

# Define the function and its operation
def square(x):
    # Printing the thread ID for the function
    print ('Function PID :', os.getppid())
    return x**x

if __name__ == '__main__':
    print ('Main Function PID :', os.getppid())
    # Define the dataset
    dataset = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

    # Output the dataset
    print ('Dataset: ' + str(dataset))

    # Run this with a pool of 5 agents having a chunksize of 3 until finished
    agents = 5
    chunksize = 3
    with Pool(processes=agents) as pool:
        result = pool.map(square, dataset, chunksize)

    # Output the result
    print ('Result:  ' + str(result))
    print ('End of script PID :', os.getppid())
