#!/usr/bin/env python3

# Import the packages
import numpy as np
import os

print ('Start of script PID:', os.getppid())

# Define the Dataset
ds = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Output the dataset
print ('Dataset: ' + str(ds))

#Perform the math operation ds^ds
y = ds**ds

# Print the Output Dataset
print ('Results: ' + str(y))

print ('End of script PID:', os.getppid())
